[build]
  base = "frontend"
  publish = "build"
  command = "npm run build"

[build.environment]
  REACT_APP_API_URL = "/.netlify/functions/api"

[functions]
  directory = "backend/functions"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
